### ISSUE TITLE
Name/Tag/ID for all resources

### ISSUE THREAD

**Issue by grahamjenson** [coinbase/odin#4]
Allow all resources to be described with a name, a name tag or ID (given AWS support of tags). This will allow releases to reference resources how they need to.

**Comment by StevenACoffman** [comment]
We use tags on EC2 instances and ASGs for cost tracking purposes.

For instance, we have a tag name like 'team' with a value like 'RedTeam',etc.:
```
app:frontend
team:ReadTeam
environment:prod
```
Being able to set that would be very handy.

**Comment by grahamjenson** [comment]
You can, using the `tags:` key on service. 

This issue is about being able to reference ELBs/TargetGroups using their name tags. This makes it easier to control as Name tags are very easy to change.
