### ISSUE TITLE
ELB's supported

### ISSUE THREAD

**Issue by chadbean** [coinbase/odin#5]
It looks like this supports application load balancers on AWS, but does it also support classic ELB's and/or network load balancers? Didn't see anything in the README/docs so I thought I'd check here.

**Comment by grahamjenson** [comment]
It supports both Classic ELBs and ALB/NLB target_groups. The way new ELBs()ALB/NLB) are attached is via target_groups, which define ports, health checks... This means that you could have multiple projects and/or configs attached to the same ALB or NLB, but not a classic ELB.

**Comment by chadbean** [comment]
Awesome 👍 

If I were to create a PR to indicate that, should it go in the README?

**Comment by grahamjenson** [comment]
Yup, some further description under the first example would be great.
